version: '3'
services:
  # MYSQL用のコンテナ
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_USER=docker
      - MYSQL_DATABASE=lvsmpr
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
     - mysql-data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 3000:80
    depends_on:
      - app
    volumes:
      - ./:/app

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/app
    links:
      - db

volumes:
  mysql-data:
   driver: local